### ISSUE TITLE
Run all tests fail

### ISSUE THREAD

**Issue by Luigie** [timdeschryver/HowToTestYourCsharpWebApi#1]
Hello Tim,
Thanks for the good example for E2E testing.

I have this this issue that running all my tests are failing. individually they are all okay.

![image](https://user-images.githubusercontent.com/667265/132513008-ad33b92e-542d-4eeb-b1af-36c414365833.png)

![image](https://user-images.githubusercontent.com/667265/132513165-9a7ed96b-c99b-457d-a2fa-10c9d21e8690.png)

 public class ApiWebApplicationFactory : WebApplicationFactory<Startup>
    {
        public IConfiguration Configuration { get; private set; }

        protected override void ConfigureWebHost(IWebHostBuilder builder)
        {

            builder.ConfigureAppConfiguration(config =>
            {
                Configuration = new ConfigurationBuilder()
                    .AddJsonFile("settings.json")
                    .Build();

                config.AddConfiguration(Configuration);
            });

            // will be called after the `ConfigureServices` from the Startup
            builder.ConfigureTestServices(services =>
            {
                services.AddTransient<IDbContextFactory, DbContextFactoryStub>();

            });

            builder.ConfigureTestServices(services =>
            {
                MvcServiceCollectionExtensions.AddControllers(services, options => options.Filters.Add(new AllowAnonymousFilter()));
            });
        }

    }

 public abstract class IntegrationTestBase : IClassFixture<ApiWebApplicationFactory>
    {
        public readonly Checkpoint Checkpoint = new Checkpoint
        {
            SchemasToInclude = new[] {
                "BLD"
            },
            WithReseed = true,
        };

        protected readonly ApiWebApplicationFactory factory;
        protected readonly IDbContextFactory dbContextFactory;
        protected readonly HttpClient client;

        public IntegrationTestBase( ApiWebApplicationFactory fixture)
        {
            factory = fixture;
            client = factory.CreateClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", GetToken());
            dbContextFactory = (DbContextFactoryStub)factory.Services.GetService(typeof(IDbContextFactory));
            Checkpoint.Reset(factory.Configuration.GetSection("ConnectionStrings:SQL").Value).GetAwaiter().GetResult();
        }
}

**Comment by timdeschryver** [comment]
Hi @Luigie, sadly I can't provide an answer based on the information.
Have you tried to debug the second test?

**Comment by timdeschryver** [comment]
Also, make sure that you [don't run your tests in parallel](https://timdeschryver.dev/blog/how-to-test-your-csharp-web-api#parallel-tests)

**Comment by Luigie** [comment]
Hello Tim,

okay the problem was that the xunit.runner.json file was not existing.

Thx
